{% set name = "minimal_molview" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/minimal_molview-{{ version }}.tar.gz
  sha256: 996e2b71635502e460fb2f6fc9e8c3cc5c670cb982d10df2c5a9aff2fba37b62

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  entry_points:
    - "minimal_molview = minimal_molview.render:main"

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - versioningit >=2.0,<3.dev0
    - pip
  run:
    - python >={{ python_min }}
    - jinja2

test:
  imports:
    - minimal_molview
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hmacdope/minimal_molview
  summary: A minimal molecular viewer for visualising molecular structures in an HTML file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmacdope
